//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newprac2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.prac2form1service1Soap")]
    public interface prac2form1service1Soap {
        
        // CODEGEN: Generating message contract since element name n from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/datefinder", ReplyAction="*")]
        newprac2.ServiceReference1.datefinderResponse datefinder(newprac2.ServiceReference1.datefinderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/datefinder", ReplyAction="*")]
        System.Threading.Tasks.Task<newprac2.ServiceReference1.datefinderResponse> datefinderAsync(newprac2.ServiceReference1.datefinderRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        newprac2.ServiceReference1.HelloWorldResponse HelloWorld(newprac2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<newprac2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(newprac2.ServiceReference1.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class datefinderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="datefinder", Namespace="http://tempuri.org/", Order=0)]
        public newprac2.ServiceReference1.datefinderRequestBody Body;
        
        public datefinderRequest() {
        }
        
        public datefinderRequest(newprac2.ServiceReference1.datefinderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class datefinderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string n;
        
        public datefinderRequestBody() {
        }
        
        public datefinderRequestBody(string n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class datefinderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="datefinderResponse", Namespace="http://tempuri.org/", Order=0)]
        public newprac2.ServiceReference1.datefinderResponseBody Body;
        
        public datefinderResponse() {
        }
        
        public datefinderResponse(newprac2.ServiceReference1.datefinderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class datefinderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string datefinderResult;
        
        public datefinderResponseBody() {
        }
        
        public datefinderResponseBody(string datefinderResult) {
            this.datefinderResult = datefinderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public newprac2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(newprac2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public newprac2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(newprac2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface prac2form1service1SoapChannel : newprac2.ServiceReference1.prac2form1service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class prac2form1service1SoapClient : System.ServiceModel.ClientBase<newprac2.ServiceReference1.prac2form1service1Soap>, newprac2.ServiceReference1.prac2form1service1Soap {
        
        public prac2form1service1SoapClient() {
        }
        
        public prac2form1service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public prac2form1service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public prac2form1service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public prac2form1service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        newprac2.ServiceReference1.datefinderResponse newprac2.ServiceReference1.prac2form1service1Soap.datefinder(newprac2.ServiceReference1.datefinderRequest request) {
            return base.Channel.datefinder(request);
        }
        
        public string datefinder(string n) {
            newprac2.ServiceReference1.datefinderRequest inValue = new newprac2.ServiceReference1.datefinderRequest();
            inValue.Body = new newprac2.ServiceReference1.datefinderRequestBody();
            inValue.Body.n = n;
            newprac2.ServiceReference1.datefinderResponse retVal = ((newprac2.ServiceReference1.prac2form1service1Soap)(this)).datefinder(inValue);
            return retVal.Body.datefinderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<newprac2.ServiceReference1.datefinderResponse> newprac2.ServiceReference1.prac2form1service1Soap.datefinderAsync(newprac2.ServiceReference1.datefinderRequest request) {
            return base.Channel.datefinderAsync(request);
        }
        
        public System.Threading.Tasks.Task<newprac2.ServiceReference1.datefinderResponse> datefinderAsync(string n) {
            newprac2.ServiceReference1.datefinderRequest inValue = new newprac2.ServiceReference1.datefinderRequest();
            inValue.Body = new newprac2.ServiceReference1.datefinderRequestBody();
            inValue.Body.n = n;
            return ((newprac2.ServiceReference1.prac2form1service1Soap)(this)).datefinderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        newprac2.ServiceReference1.HelloWorldResponse newprac2.ServiceReference1.prac2form1service1Soap.HelloWorld(newprac2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            newprac2.ServiceReference1.HelloWorldRequest inValue = new newprac2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new newprac2.ServiceReference1.HelloWorldRequestBody();
            newprac2.ServiceReference1.HelloWorldResponse retVal = ((newprac2.ServiceReference1.prac2form1service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<newprac2.ServiceReference1.HelloWorldResponse> newprac2.ServiceReference1.prac2form1service1Soap.HelloWorldAsync(newprac2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<newprac2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            newprac2.ServiceReference1.HelloWorldRequest inValue = new newprac2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new newprac2.ServiceReference1.HelloWorldRequestBody();
            return ((newprac2.ServiceReference1.prac2form1service1Soap)(this)).HelloWorldAsync(inValue);
        }
    }
}
